### ISSUE TITLE
Create indexes necessary for sorting + filtering of multiple fields

### ISSUE THREAD

**Issue by DracoBlue** [DracoBlue/payload-firestore-adapter#20]
In non-Emulators want to have indexes created for descending sorting.

- add admin api logic to create id, createdAt, updatedAt indexes for descending by default

**Comment by DracoBlue** [comment]
Added this test for testing:

```
  ● firestore adapter tests › order collection items and filter by publisher [fails on non-emulator]

    FAILED_PRECONDITION: no matching index found. recommended index is:
    - kind: books
      properties:
      - name: publisher
      - name: id

  ● firestore adapter tests › order and filter collection items by id

    9 FAILED_PRECONDITION: no matching index found. recommended index is:
    - kind: books
      properties:
      - name: id
      - name: id
     
  ● firestore adapter tests › order and filter collection items by -id

    9 FAILED_PRECONDITION: no matching index found. recommended index is:
    - kind: books
      properties:
      - name: id
      - name: id
        direction: desc

 ● firestore adapter tests › order and filter collection items by default which is -id

    9 FAILED_PRECONDITION: no matching index found. recommended index is:
    - kind: books
      properties:
      - name: id
      - name: id
        direction: desc

  ● firestore adapter tests › should query non-hasMany within an group

    9 FAILED_PRECONDITION: no matching index found. recommended index is:
    - kind: books
      properties:
      - name: group.text
      - name: createdAt
        direction: desc
```
